-- MA KHACH HANG, TEN KHACH HANG, SO DIEN THOAI CO NAM SINH 1960 DA MUA SAN PHAM SAN XUAT TAI 'VIETNAM' NAM 2020 TAI CHI NHANH 1 VA MASP, TEN SP TUONG UNG

SELECT /*+ GATHER_PLAN_STATISTICS */ KH.MAKH, HOTEN, SODT , SP.MASP, TENSP
FROM KHACHHANG KH, SANPHAM SP, HOADON HD, CTHD, CHINHANH CN
WHERE HD.MAKH = KH.MAKH
AND HD.SOHD = CTHD.SOHD
AND CTHD.MASP = SP.MASP
AND CN.MACHINHANH = HD.MACHINHANH
AND extract(year from NGSINH) = 1960
AND extract(year from NGHD) = 2020
AND NUOCSX = 'VIETNAM'
AND HD.MACHINHANH = 'CN1'
ORDER BY KH.MAKH;

SELECT *
FROM table(DBMS_XPLAN.DISPLAY_CURSOR(FORMAT=>'ALLSTATS LAST ALL +OUTLINE'));


SELECT /*+ GATHER_PLAN_STATISTICS */ A1.MAKH, HOTEN, SODT, MASP, TENSP
FROM (
	(SELECT MAKH, MASP, TENSP
	FROM (
		(SELECT SOHD, SP.MASP, TENSP
		FROM (
			(SELECT MASP TENSP
			FROM SANPHAM
			WHERE NUOCSX='VIETNAM'
			) SP
			INNER JOIN
			(SELECT SOHD, MAKH
			FROM CTHD
			)
			ON SP.MASP = CTHD.MASP
		)
		) B1
		INNER JOIN
		(SELECT SOHD, MAKH
		FROM (
			(SELECT MACHINHANH
			FROM CHINHANH
			WHERE MACHINHANH = 'CN1'
			) CN
			INNER JOIN
			(SELECT SOHD, MACHINHANH, MAKH
			FROM HOADON
			WHERE extract(year from NGHD) = 2020
			) HD
			ON CN.MACHINHANH = HD.MACHINHANH
		)
		) B2
		ON B1.SOHD = B2.SOHD
	)
	) A1
	INNER JOIN
	(SELECT MAKH, HOTEN, SODT
	FROM KHACHHANG
	WHERE extract(year from NGSINH) = 1960
	) A2
	ON A1.MAKH = A2.MAKH
)
ORDER BY A1.MAKH;